# LCS 

In [9]:
import numpy as np

In [61]:
def LCS(s1, s2):
    # initialize state
    n, m = len(s1) + 1, len(s2) + 1
    dp =   [
        [ 0 for _ in range(m)] 
        for _ in range(n)
    ]
    pred = [
        [ (-1,-1) for _ in range(m)]
        for _ in range(n)
    ]
    
    for i in range(1,n):
        for j in range(1,m):
            # CASE 1: ignore character in s1
            dp[i][j], pred[i][j] = dp[i-1][j], (i-1,j)
            # CASE 2: ignore character in s2
            if dp[i][j] < dp[i][j-1]:
                dp[i][j], pred[i][j] = dp[i][j-1], (i,j-1)
            # CASE 3: extend
            if s1[i-1] == s2[j-1] and dp[i][j] < dp[i-1][j-1] + 1:
                dp[i][j], pred[i][j] = dp[i-1][j-1] + 1, (i-1,j-1)
    
    print (np.array(dp))

    # recover the solution
    x,y = (n-1,m-1)
    solution = []
    while pred[x][y] != (-1,-1):
        if pred[x][y] == (x-1, y-1):
            solution.append(s1[x-1])
        (x,y) = pred[x][y]
    solution.reverse()
    
    return solution

In [62]:
LCS("bacb", "babd")

[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 2 2 2]
 [0 1 2 2 2]
 [0 1 2 3 3]]


['b', 'a', 'b']

In [63]:
LCS("isthislcs", "thisislcs")

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 1 1 1 1]
 [0 0 0 1 2 2 2 2 2 2]
 [0 1 1 1 2 2 2 2 2 2]
 [0 1 2 2 2 2 2 2 2 2]
 [0 1 2 3 3 3 3 3 3 3]
 [0 1 2 3 4 4 4 4 4 4]
 [0 1 2 3 4 4 4 5 5 5]
 [0 1 2 3 4 4 4 5 6 6]
 [0 1 2 3 4 4 5 5 6 7]]


['t', 'h', 'i', 's', 'l', 'c', 's']

# Viterbi algorithm

In [1]:
states = ('Healthy', 'Fever')
 
observations = ('normal', 'cold', 'dizzy')
 
start_probability = {'Healthy': 0.6, 'Fever': 0.4}
 
transition_probability = {
   'Healthy' : {'Healthy': 0.7, 'Fever': 0.3},
   'Fever' : {'Healthy': 0.4, 'Fever': 0.6}
   }
 
emission_probability = {
   'Healthy' : {'normal': 0.5, 'cold': 0.4, 'dizzy': 0.1},
   'Fever' : {'normal': 0.1, 'cold': 0.3, 'dizzy': 0.6}
}

In [7]:
def viterbi(obs, states, start_p, trans_p, emit_p):
    V = [{}]
    predecessor = [{}]
    
    # Initialize base cases (t == 0)
    for y in states:
        V[0][y] = start_p[y] * emit_p[y][obs[0]]
        predecessor[0][y] = None
    
    # Run Viterbi for t > 0
    for t in range(1, len(obs)):
        V.append({})
        predecessor.append({})

        for y in states:
            highest_probability, best_y_prev = 0.0, None
            for y_prev in states:
                probability_from_y_prev = V[t-1][y_prev] * trans_p[y_prev][y] * emit_p[y][obs[t]]
                if probability_from_y_prev > highest_probability:
                    highest_probability, best_y_prev = probability_from_y_prev, y_prev
            V[t][y] = highest_probability
            predecessor[t][y] = best_y_prev
    
    print(*dptable(V), sep='')
    
    # Return the most likely sequence over the given time frame
    n = len(obs) - 1
    (prob, state) = max((V[n][y], y) for y in states)
    
    # Recover the path
    path = []
    for t in range(n,-1,-1):
        path.append(state)
        state = predecessor[t][state]
    path.reverse()
    
    return (prob, path)

# Don't study this; it just prints a table of the steps.
def dptable(V):
    yield "    "
    yield " ".join(("%7d" % i) for i in range(len(V)))
    yield "\n"
    for y in V[0]:
        yield "%.5s: " % y
        yield " ".join("%.7s" % ("%f" % v[y]) for v in V)
        yield "\n"

In [8]:
viterbi(observations, states, start_probability, transition_probability, emission_probability)

          0       1       2
Fever: 0.04000 0.02700 0.01512
Healt: 0.30000 0.08400 0.00588



(0.01512, ['Healthy', 'Healthy', 'Fever'])